### ISSUE TITLE
FL with TFF

### ISSUE THREAD

**Issue by pengyuan-zhou** [zouyu4524/fl-android#2]
Hi, 

Thanks for sharing the great work.
I just started to work on FL, do you know any code for TFF based FL on android?

BR

**Comment by zouyu4524** [comment]
Hi,

It's been a while that I haven't checked on the TFF development progress. Back in May 2019, TFF seems not suitable for on-device **training**, neither PyTorch back then. That was why I choose DL4J for this project. The situation may have changed now.

BR

**Comment by pengyuan-zhou** [comment]
> Hi,
> 
> It's been a while that I haven't checked on the TFF development progress. Back in May 2019, TFF seems not suitable for on-device **training**, neither PyTorch back then. That was why I choose DL4J for this project. The situation may have changed now.
> 
> BR

Thanks, ya seems still not
https://www.tensorflow.org/federated/faq#can_tensorflow_federated_be_used_in_production_setting_eg_on_mobile_phones
